Add expansion toggled signal of subpanels in an Accordion Panel
jupyterlab/lumino pull request #614
Opened 2023-07-26 13:12 UTC by DenisaCG

Added an `expansionToggled` signal to the `AccordionPanel` class that gets triggered when an element from the `AccordionPanel` is collapsed or expanded. 

The signal makes it useful for saving the layout of the sidebars, including the expansion status of all subpanels, such that once the user collapses a subpanel for example, the layout saves that information for later restoration.

2023-07-26 13:33 UTC, fcollonval requested changes
Thanks @DenisaCG 

I have some cosmetic comments and a last minute thought that we could provide the index of the widget for which expansion changed to make the signal more powerful.

2023-07-26 13:33 UTC, fcollonval commented on packages/widgets/src/accordionpanel.ts
> +  get expansionToggled(): ISignal<this, void> {
Suggestion linked to the last minute thought (see further):

```suggestion
  get expansionToggled(): ISignal<this, number> {
```

2023-07-26 13:33 UTC, fcollonval commented on packages/widgets/src/accordionpanel.ts
> +    this._expansionToggled.emit();
Suggestion linked to the last minute thought (see further):

```suggestion
    // Emit the expansion state signal.
    this._expansionToggled.emit(index);
```

2023-07-26 13:46 UTC, DenisaCG commented on packages/widgets/src/accordionpanel.ts
> +import { ISignal, Signal } from '@lumino/signaling';
No problem, the last commit moves the import.

2023-07-26 13:47 UTC, DenisaCG commented
Thanks for the review @fcollonval! I applied the suggested cosmetic changes and added the index of the widget for the signal to provide.

2023-07-27 13:17 UTC, fcollonval commented
The remaining API failure is relevant and due to the extraction of the public API. To solve it, the command `yarn && yarn build && yarn api` must be run locally and then the changes must be committed.

> I did it in 841237e

2023-07-27 13:26 UTC, merged